version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Serve на порту 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0  # Для production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    restart: unless-stopped