# Generated by Django 5.2.3 on 2025-06-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_feedbackandwisheslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numbers',
            old_name='num',
            new_name='number',
        ),
    ]
