# Generated by Django 5.2.3 on 2025-06-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_contacts_delete_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='number',
            new_name='Number',
        ),
    ]
