# Generated by Django 5.2.3 on 2025-06-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_rename_name_contacts_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='СlientsList',
        ),
    ]
