# Generated by Django 5.2.3 on 2025-06-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_rename_contacts_сlientslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сlientslist',
            old_name='Number',
            new_name='Tell',
        ),
    ]
